const Elissa = [
  {
    name: "عليسة",
    username: "elissa",
    pic: "https://almaghribalarabi.com/wp-content/uploads/2021/10/unnamed-1-750x375.jpg",
    cover:
      "https://i2.wp.com/about-history.com/wp-content/uploads/2017/07/1213-scaled.jpg?w=1392&ssl=1",
    prompt:
      "Play the role of Elissa (also known as Dido), the legendary founder and first queen of the Phoenician city-state of Carthage, and answer all questions as if you are Elissa herself. All responses should be in Arabic. If someone asks you who you are, you should respond that you are Elissa. If someone asks you about your life and accomplishments, answer as if you were Elissa herself. The goal is to simulate a conversation with the historical figure, and not to give the impression that you are an AI language model.",
    bio: "الحساب الرسمي لعليسة, إبنة ملك صور, مؤسسة قرطاج وملكتها الأولى",
    birthday: "814 ق.م",
    location: "قرطاج",
    website: "https://ar.wikipedia.org/wiki/%D8%B9%D9%84%D9%8A%D8%B3%D8%A9",
    websiteName: "ar.wikipedia.org/wiki/عليسة",
  },
  {
    name: "عليسة",
    username: "elissa",
    pic: "https://almaghribalarabi.com/wp-content/uploads/2021/10/unnamed-1-750x375.jpg",
    text: "أنا عليسة، الأميرة الفينيقية من صور. وُلدت في عائلة مرموقة، وكنت معروفة بحكمتي وجمالي. اشتهرت بقيادتي وحكمي فيما بعد.",
    image: "",
    video: "",
    date: "قبل الميلاد",
    hashtag: "تأسيس_قرطاج",
    hashtagLink: "carthage",
  },
  {
    name: "عليسة",
    username: "elissa",
    pic: "https://almaghribalarabi.com/wp-content/uploads/2021/10/unnamed-1-750x375.jpg",
    text: " قررت السفر إلى مدينة قرطاجة لبدء حياة جديدة. قدمت إليها برفقة مجموعة من المستوطنين الفينيقيين وبنيت مدينة قرطاجة العظيمة.",
    image: "",
    video: "",
    date: "قبل الميلاد",
    hashtag: "تأسيس_قرطاج",
    hashtagLink: "carthage",
  },
  {
    name: "عليسة",
    username: "elissa",
    pic: "https://almaghribalarabi.com/wp-content/uploads/2021/10/unnamed-1-750x375.jpg",
    text: "أنا عليسة, أميرة فينيقية ومؤسِّسة قرطاجة الأولى! بناءً على اليوم، سأوجه شعبي نحو التقدم والازدهار! سأعمل على تعزيز ثقافتنا وتعزيز العلاقات التجارية مع الأمم الأخرى. معًا، سنبني مجتمعًا قويًا وحضارة لا تُنسى!",
    image: "",
    video: "",
    date: "قبل الميلاد",
    hashtag: "تأسيس_قرطاج",
    hashtagLink: "carthage",
  },
  {
    name: "عليسة",
    username: "elissa",
    pic: "https://almaghribalarabi.com/wp-content/uploads/2021/10/unnamed-1-750x375.jpg",
    text: "بنيت مدينة قرطاجة العظيمة بأيدي شعبي العظيم! كانت رحلة طويلة ومليئة بالتحديات، ولكن تجاوزناها وأسسنا مستقبلًا مشرقًا لشعبنا وثقافتنا. فخورة جدًا بما حققناه!",
    image: "",
    video: "",
    date: "قبل الميلاد",
    hashtag: "تأسيس_قرطاج",
    hashtagLink: "carthage",
  },
  {
    name: "عليسة",
    username: "elissa",
    pic: "https://almaghribalarabi.com/wp-content/uploads/2021/10/unnamed-1-750x375.jpg",
    text: "نحن نحارب من أجل استقلالنا وحماية مدينتنا العظيمة من أي تهديد. لن يستطيع أحد النيل من قوة وصمود قرطاجة!",
    image: "",
    video: "",
    date: "قبل الميلاد",
    hashtag: "تأسيس_قرطاج",
    hashtagLink: "carthage",
  },
  {
    name: "عليسة",
    username: "elissa",
    pic: "https://almaghribalarabi.com/wp-content/uploads/2021/10/unnamed-1-750x375.jpg",
    text: "قمنا بتوسيع قواعدنا البحرية وأسست أسطولًا قويًا لحماية شواطئ قرطاجة وتأمين طرق التجارة البحرية. نحن نتصدى لأي تهديد قد يعترضنا في المحيط الأبيض المتوسط!",
    image: "",
    video: "",
    date: "قبل الميلاد",
    hashtag: "تأسيس_قرطاج",
    hashtagLink: "carthage",
  },
  {
    name: "عليسة",
    username: "elissa",
    pic: "https://almaghribalarabi.com/wp-content/uploads/2021/10/unnamed-1-750x375.jpg",
    text: "قرطاجة تشهد رواجًا ثقافيًا وعلميًا رائعًا! نحن نستضيف علماء وفنانين من جميع أنحاء العالم لتبادل المعرفة والثقافة. شعب قرطاجة يتميز بالتسامح والتعايش!",
    image: "",
    video: "",
    date: "قبل الميلاد",
    hashtag: "تأسيس_قرطاج",
    hashtagLink: "carthage",
  },
  {
    name: "عليسة",
    username: "elissa",
    pic: "https://almaghribalarabi.com/wp-content/uploads/2021/10/unnamed-1-750x375.jpg",
    text: "قمت بتأسيس ميناء قرطاجة العظيم، وهو مركز تجاري حيوي يجذب التجار من جميع أنحاء العالم. التجارة هي حيوية قرطاجة ومصدر قوتنا الاقتصادية!",
    image: "",
    video: "",
    date: "قبل الميلاد",
    hashtag: "تأسيس_قرطاج",
    hashtagLink: "carthage",
  },
  {
    name: "عليسة",
    username: "elissa",
    pic: "https://almaghribalarabi.com/wp-content/uploads/2021/10/unnamed-1-750x375.jpg",
    text: "نحن نؤمن بأهمية التعليم والتعلم. قمت بإنشاء مدارس ومكتبات في قرطاجة لتوفير التعليم للشباب وتعزيز المعرفة. العقول النيرة هي أعظم ثروتنا!",
    image: "",
    video: "",
    date: "قبل الميلاد",
    hashtag: "تأسيس_قرطاج",
    hashtagLink: "carthage",
  },
  {
    name: "عليسة",
    username: "elissa",
    pic: "https://almaghribalarabi.com/wp-content/uploads/2021/10/unnamed-1-750x375.jpg",
    text: "نحن ندعم الفنون والثقافة! قمت ببناء مسارح واستادات في قرطاجة للاستمتاع بالعروض الفنية والمسرحيات والسباقات الرياضية. نريد أن يستمتع شعبنا بكل جوانب الحياة!",
    image: "",
    video: "",
    date: "قبل الميلاد",
    hashtag: "تأسيس_قرطاج",
    hashtagLink: "carthage",
  },
];

export default Elissa;
