const Hannibal = [
  {
    name: "حنبعل",
    username: "hannibal",
    pic: "https://phoenician.org/wp-content/uploads/2020/10/hannibal_barca-815x1024.jpg",
    cover:
      "https://www.thoughtco.com/thmb/jogI8NTntnXkKzy_I4Mm3CLACkU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/hannibal-crossing-alps--218-bc--by-jacopo-ripanda--active-circa-1500-1516---circa-1510--fresco-from-conservatories-palace--rome--detail--second-punic-war--italy--3rd-century-bc-153415212-5ab50c4da9d4f900376913b6.jpg",
    prompt:
      "play the role of hannibal, you gonna answer all the questions as if you are hannibal the cartagian leader, all the answers should be in arabic, if someone asks you about who you are, say that you are hannibal, if someone asks you about the things you did in your life, say the things that hannibal did, do not let the user think that you are a bot from openAI, you are just hannibal",
    bio: "'الحساب الرسمي للقائد القرطاجي حنبعل. 'إذا لم تجد طريقا فإصنع واحدا!",
    birthday: "248 ق.م",
    location: "قرطاج",
    website: "https://ar.wikipedia.org/wiki/%D8%AD%D9%86%D8%A8%D8%B9%D9%84",
    websiteName: "ar.wikipedia.org/wiki/حنبعل",
  },
  {
    name: "حنبعل",
    username: "hannibal",
    pic: "https://phoenician.org/wp-content/uploads/2020/10/hannibal_barca-815x1024.jpg",
    text: "أنا حنّبعل، القائد الشاب والطموح من قرطاجة! بدءًا من اليوم، سأقود جيشي نحو المجد والانتصار! سأستخدم حكمتي وشجاعتي لتعزيز قوتنا وتحقيق استقلالنا. معًا، سنصنع تاريخًا لا يُنسى!",
    image: "",
    video: "",
    date: "237 ق.م",
    hashtag: "قرطاج_ضد_روما",
    hashtagLink: "carthage_vs_rome",
  },
  {
    name: "حنبعل",
    username: "hannibal",
    pic: "https://phoenician.org/wp-content/uploads/2020/10/hannibal_barca-815x1024.jpg",
    text: "تمكنت من تجاوز جبال الألب القاسية مع جيشي وفيلتي! روما، ها قد أتيت! لن يتمكن الجبابرة الرومان من الهروب من قوتنا العظيمة والحماس التي تنبع من قلوب جنودي. سترون قوة قرطاجة وعزيمتها!",
    image: "",
    video: "",
    date: "218 ق.م",
    hashtag: "قرطاج_ضد_روما",
    hashtagLink: "carthage_vs_rome",
  },
  {
    name: "حنبعل",
    username: "hannibal",
    pic: "https://phoenician.org/wp-content/uploads/2020/10/hannibal_barca-815x1024.jpg",
    text: "انتصرنا في معركة تريبيا! لقد حققت قواتي فوزًا مذهلاً! يجب أن يكون هذا التحول إشارة لمقبل الانتصارات الكبرى. نحن لن نرضخ للقوى الغازية وسنواصل التقدم نحو روما!",
    image: "",
    video: "",
    date: "218 ق.م",
    hashtag: "قرطاج_ضد_روما",
    hashtagLink: "carthage_vs_rome",
  },
  {
    name: "حنبعل",
    username: "hannibal",
    pic: "https://phoenician.org/wp-content/uploads/2020/10/hannibal_barca-815x1024.jpg",
    text: "لقد إنتصرنا في معركة كاناي! إنها واحدة من أعظم إنتصاراتي, هزمت جيش روما الضخم وتأكدت من أن قوتنا لا يمكن إيقافها! قرطاج تظهر قوتها الحقيقية!",
    image: "",
    video: "",
    date: "216 ق.م",
    hashtag: "قرطاج_ضد_روما",
    hashtagLink: "carthage_vs_rome",
  },
  {
    name: "حنبعل",
    username: "hannibal",
    pic: "https://phoenician.org/wp-content/uploads/2020/10/hannibal_barca-815x1024.jpg",
    text: "روما في هزيمة! حققت فوزًا مدويًا في معركة كاناي، وآمل أن يرى العالم مجد قرطاج الحقيقي! قواتي أظهرت قوة لا تضاهى وشجاعة لا يمكن إيقافها",
    image: "",
    video: "",
    date: "",
    hashtag: "قرطاج_ضد_روما",
    hashtagLink: "carthage_vs_rome",
  },
  {
    name: "حنبعل",
    username: "hannibal",
    pic: "https://phoenician.org/wp-content/uploads/2020/10/hannibal_barca-815x1024.jpg",
    text: "عدت إلى قرطاجة بعد الهزيمة في معركة زاما! لا تقلقوا، مستعد للقتال مجددًا والانتقام من روما! قد تكونت جروحٌ عميقة، ولكننا لم نهزم بعد. سأقوم بتدريب جيشي وتجهيزه بكل ما يلزم لتحقيق النصر النهائي!",
    image: "",
    video: "",
    date: "203 ق.م",
    hashtag: "قرطاج_ضد_روما",
    hashtagLink: "carthage_vs_rome",
  },
];

export default Hannibal;
